"use client";

import { Card, CardBody, useDisclosure } from "@nextui-org/react";
import confetti from "canvas-confetti";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import Footer from "./components/footer/footer";
import ResultTable from "./components/resultTable";
import Searchbar from "./components/searchbar";
import VictoryModal from "./components/victoryModal";
import { ACard, findCards, getRandomCard } from "./service/cardsService";

const Home: NextPage = () => {
  const [cardToGuess, setCardToGuess] = useState<ACard | null>(null);
  const [cards, setCards] = useState<ACard[]>([]);
  const [searchbarPlaceholder, setSearchbarPlaceholder] = useState<string>("");
  const [cardsGuessed, setCardsGuessed] = useState<ACard[]>([]);
  const { isOpen, onOpen, onOpenChange } = useDisclosure();
  const handleConfetti = () => {
    confetti({ zIndex: 1000 });
  };
  const victory = () => {
    onOpen();
    handleConfetti();
  };

  const onUserSelectCard = (card: ACard) => {
    if (cardToGuess!.id === card.id) {
      victory();
    }
    setCardsGuessed(
      [...cardsGuessed, card].filter((card) => card != undefined),
    );
  };
  useEffect(() => {
    const fetchCards = findCards();
    setCards(fetchCards);

    if (fetchCards.length > 0) {
      const randomCard = getRandomCard(fetchCards);
      setCardToGuess(randomCard);
      setSearchbarPlaceholder(
        `${getRandomCard(fetchCards).name}, ${getRandomCard(fetchCards).name}, ${getRandomCard(fetchCards).name}`,
      );
    }
  }, []);
  return (
    <div>
      <div id="page">
        <div id="content">
          <main className="flex flex-1 w-full flex-col items-center justify-center text-center px-4 sm:mt-20 mt-20 ">
            <h1 className="mx-auto max-w-4xl font-display text-5xl font-bold tracking-normal text-gray-300 sm:text-7xl">
              <span className="relative whitespace-nowrap text-blue-600">
                <div className="flex flex-col  gap-4">
                  <span className="h-16 w-16  ">{"Devine"}</span>
                </div>
              </span>{" "}
              la carte du jour
            </h1>

            <div className="flex justify-center mt-10 items-center px-3">
              <VictoryModal
                card={cardToGuess!}
                isOpen={isOpen}
                onOpenChange={onOpenChange}
              ></VictoryModal>
              <Head>
                <meta
                  name="description"
                  content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
              </Head>

              <main className="flex flex-col items-center">
                <Card className="w-full justify-items-center self-center	">
                  <CardBody className="p-5">
                    <Searchbar
                      cardsGuessed={cardsGuessed}
                      placeholder={searchbarPlaceholder}
                      cards={cards}
                      onUserSelectCard={onUserSelectCard}
                    ></Searchbar>

                    <ResultTable
                      cardToGuess={cardToGuess!}
                      cardsGuessed={cardsGuessed}
                    ></ResultTable>
                  </CardBody>
                </Card>
              </main>
            </div>
          </main>
        </div>
        <Footer></Footer>
      </div>
    </div>
  );
};

export default Home;
